config/routes.rb
Rails.application.routes.draw do
root :to => 'users#welcome'

resources :user_sessions
resources :users

resources :tasks do
	resources :submissions
end

resources :photo_tasks do
  resources :submissions
end

resources :answer_tasks do
  resources :submissions
end


get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

get 'about' => 'tasks#about'

end

app/models/answer_task.rb
class AnswerTask < Task
  validates :answer, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo_task.rb
class PhotoTask < Task
  validates :image_string, presence: true
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :user
  belongs_to :task
  mount_uploader :image_string, ImageStringUploader

end

app/models/task.rb
class Task < ApplicationRecord
	has_many :submissions
	has_many :users, through: :submissions

	accepts_nested_attributes_for :submissions
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  has_many :submissions
  has_many :tasks, through: :submissions

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) || User.where(guest_token: guest_token).first_or_initialize.tap do |user|
    	user.email = guest_token
    	user.guest_token = guest_token
      if user.username == nil
        user.username = RandomUsername.username
      end
    	user.save(validate: false) if user.new_record?
    end
  end

  def guest_token
  	session[:guest_token]||= SecureRandom.hex(24)
  end

  helper_method :current_user

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :load_task

  def new
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(submission_params)

    @submission.user = current_user
    @submission.task = @task
    if @submission.user.score == nil
      @submission.user.score = 0
    end


    case @task.task_type
    when 'answer_tasks'
      if @submission.answer.downcase != @task.answer.downcase
        redirect_to tasks_path, notice: "Sorry! Try Again!"
      elsif @submission.save
        @submission.user.score += @task.points
        @submission.user.update(score: @submission.user.score)
        redirect_to tasks_path, notice: 'Woohoo! You got it!'
      else
        redirect_to tasks_path, notice: 'Ooops! Something went terribly wrong!'
      end
    when"photo_tasks"
    if @submission.image_string != nil && @submission.save
      @submission.user.save
      redirect_to tasks_path, notice:"Cool Stuff!"
    elsif @submission.image_string = nil
      return redirect_to tasks_path, notice:"Your Art is too deep!Try a picture instead!"

    else
      redirect_to tasks_path, notice: "Ooops! Something went terribly wrong!"
    end
    end
  end

  def edit
    @submission = Submission.find(params[:id])
  end

  def update
    @submission = Submission.find(params[:id])
    if @submission.update
      redirect_to tasks_path, notice: 'Awesome! You got it!'
    else
      render :edit, notice: 'Not quite! Give it another go!'
    end
  end

    private

    def submission_params
      params.require(:submission).permit(:name, :task_id, :user_id, :answer, :image_string)
    end

    def load_task
      @task = Task.find(params[:task_id] || params[:answer_task_id] || params[:photo_task_id])
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_url, notice: 'Task was updated'
    else
      render :edit
    end
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :points, :answer,:task_type)
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_action :require_login, except: [:destroy]
	
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:index, :new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @highest_score = User.where("score > ?", 0).order(score: :desc)
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to tasks_path notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation, :score, :icon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-turbolinks='false'>
  <head>
    <title>The Next Super Geek</title>
      <%= stylesheet_link_tag    "application" %>
      <%= javascript_include_tag "application" %>
      <%= csrf_meta_tags %>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=deviice-width, initial-scale=1.0">
  </head>
  <body>


<div class="hamburger-container">
  <div>
    <div class="nav-logo">
      <%= image_tag "tsngChallenge.png" %>
    </div>
    <div class='score-container'>
      <%= current_user.score %>
    </div>
    <div class='icon-top'>
      <% if current_user.icon == 'boy' && current_user.score != nil %>
        <%= image_tag('icon_boy.png', size: "80x80") %>
      <% elsif current_user.icon == 'girl' && current_user.score != nil %>
        <%= image_tag('icon_girl.png', size: "80x80") %>
      <% elsif current_user.score != nil %>
        <%= image_tag('icon_profile.png', size: "80x80") %>
      <% end %>
    </div>
    <div class='username-container'>
      <% if current_user.score != nil %>
        <%= current_user.username %>
      <% end %>
    </div>

  </div>
  <aside class="sidebar">
    <nav class="side-menu-content">
      <ul class="side-menu" data-turbolinks="false">
        <li><%= link_to "LEADERBOARD", users_url %></li>
        <li><%= link_to "THE MISSION", tasks_url %></li>
        <li><%= link_to "ABOUT US", about_url %></li>
      </ul>
    </nav>
  </aside>

  <a id="nav-toggle" href="#"><span data-turbolinks='false'></span></a>
</div>

   </div>

    <div class="notification">
      <p id="notice"><%= flash[:notice] %></p>
      <p id="alert"><%= flash[:alert] %></p>
    </div>


    <%= yield %>

    <footer>
      <div class="footer">
        <hr>
        &copy;&nbsp;2016 NextSuperGeek
      </div>
    </footer>



    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Info</h4>
          </div>
          <div class="modal-body">
              <p id="notice"><%= flash[:notice] %></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div><!---modal-->

  </body>
</html>

app/views/submission/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Submission</title>
  </head>
  <body>
    <form>
    <form class="Answer" action="Answer" method="post">
      <input type="text" name="answer" value="Answer"><br>

    </form>
  </body>
</html>

<form>
  <label for="name"></label>
  <input type="text" name="name" class="contact-info" id="name" placeholder="Name">
  <label for="email"></label>
  <input type="email" name="email" class="contact-info" id="email" placeholder="Email">
  <div class="clear"></div>
  <label for="message"></label>
  <textarea name="message" id="message" placeholder="Message"></textarea>
  <input type="submit" name="submit" id="submit" value="Submit">
</form>

app/views/submissions/_form.html.erb
<%= form_for(task.submissions.build) do |f| %>
  <div class="field hidden">
    <%= f.label :name %>
    <%= f.hidden_field :name %>
  </div>

  <div class="field hidden">
    <%= f.label :task_id %>
    <%= f.hidden_field :task_id %>
  </div>

  <div class="field hidden" >
    <%= f.label :user_id %>
    <%= f.hidden_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :answer %>
    <%= f.text_field :answer %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <%= f.submit %>

<% end %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
	
	<div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/tasks/about.html.erb
<p>
	Do you roll your eyes when you have to fix your parent's computer (again)? Can you cast a Harry Potter spell while whistling the theme song from Dr. Who? Or maybe you are programming with Raspberry Pi while baking the world’s largest Raspberry Pie? If you said YES to any of these questions, then we want to hear from you!
</p>

<p>
	All summer long we will be celebrating all things Geek. Answer the questions in the form below and submit a video <%= link_to "(Here's some Inspiration!)", 'https://www.youtube.com/watch?v=87Y_WHOx_Nk&feature=youtu.be' %> or a picture showing us what kind of Geek you are. We will feature these on our website so come back and check out your fellow Geeks!
</p>

<p>
	You might be a MAKER Geek, a FILM geek, a COMIC BOOK geek or a SCI-FI GEEK...  Whatever your passion, we are looking for the gifted, the curious, and the exceptional Supergeeks of the GTA.
</p>

<div class='badge-container'>
    <%= link_to image_tag('icon_mission.png', size: '300x300', id: 'ribbon')%>
</div>

<p>
	TNSG is produced by sibling misfits, Amos and Karen Shaw. With over 15 years of producing award-winning content for the likes of Film, TV and Interwebs, the duo specializes in out-of-this-world content.
</p>

app/views/tasks/edit.html.erb
Edit Task
<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="runner">
    <%= image_tag "runner-edit.png" %>
</div>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
    <% @tasks.each do |task| %>

    <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="heading<%=task.id%>">
            <h4 class="panel-title">
                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<%=task.id%>" aria-expanded="false" aria-controls="collapse<%=task.id%>">
                    <%= task.name %>
                    <div id='points-heading'><%= task.points %>
                        Points
                        <% if task.submissions.where(user: current_user).empty? %>
                            <%=image_tag('button_radial.png', size: '32x32', class: 'checkbox') %>
                        <% else %>
                            <%=image_tag('checkbox.png', size: '32x32', class: 'checkbox') %>
                        <% end %>
                    </div>
                </a>
            </h4>
        </div>
    </div>

    <div id="collapse<%=task.id %>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading<%=task.id%>">
        <div class="panel-body">

            <%= task.description %>
            <%= form_for([task, task.submissions.build]) do |f| %>

                <div class="field" id="dropdown-heading">
                  <% if task.submissions.where(user: current_user).empty? %>

                    <% if task.task_type == "answer_tasks" %>
                      <%= f.text_field :answer %>
                      <%= f.submit "I know this!", class: 'btn btn-default' %>
                    <% end %>

                    <% if task.task_type == "photo_tasks" %>
                        <%= f.file_field :image_string %>
                        <%= f.submit "Oh Snap!", class: "btn btn-default" %>
                    <% end %>
                  <% end %>
                </div>
            <% end %>

        </div>
    </div>

    <%end%>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-default"><%= link_to "I'm done! ...for now", user_path(current_user.id) %></button>
</div>

app/views/tasks/new.html.erb
New Task

<%= form_for(@task) do |f| %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :points %><br />
    <%= f.number_field :points %>
  </div>

  <div class="field">
    <%= f.select :task_type, [['Answer','answer_tasks'],['Photo','photo_tasks']] %>
  </div>

  <div class="field">
    <%= f.label :answer %><br />
    <%= f.text_field :answer %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email, value: "" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Update Profile</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<body class='leaderboard'>
  <h1>LEADERBOARD</h1>
  <div class=''>
    <table class="table table-hover table-inverse">
      <thead class="thead-default">
        <tr>
          <th>Username</th>
          <th>Score</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @highest_score.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td><%= user.score %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <hr>
</body>
<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.submissions.count >= Task.all.count %>

  <p>
    CONGRATULATIONS <%=current_user.username%>!
  </p>

  <p>
    You have successfully completed the ROM MISSION!
  </p>

  <div class='badge-container'>
    <%= link_to image_tag('MissionBadge.png', size: '300x300', id: 'badge')%>
  </div>
  
  <p>
    Your final score was <%=current_user.score%>
  </p>

  <p>Add your info below to be eligible for the grand prize!</p>

  <p>
    Please redeem your prize at the membership desk. Visit us online to find out more about the grand prize.
  </p>

<% else %>

  <p>
    Hey <%=current_user.username%>!
  </p>

  <p>
    Your current score is <%=current_user.score%>
  </p>

  <p>
    You haven't completed the mission yet... but there's still plenty of time!
  </p>

  <p>
    If you can't finish right now, no worries! You can always come back later to finish.
  </p>

  <p>If you'd like us to let you know about future missions, events and prizes(!!!), press the button below or check us out online:</p>
<% end %>

<p>
  <%=link_to "thenextsupergeek.com", 'www.thenextsupergeek.com' %>
</p>

<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modal-fullscreen">
  Add Info
</button>

<div class="modal modal-fullscreen fade" id="modal-fullscreen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Add info</h4>
      </div>
      <div class="modal-body">

        <%= form_for current_user do |f| %>

        <fieldset id='fs-firstname'>
          <h2 class="fs-title">What's Your First Name?</h2>

            <%= f.text_field :first_name, value: "" %>

            <br>

            <input type="button" name="next" class="next action-button btn btn-default" value="Next" />

        </fieldset>

        <fieldset id='fs-lastname'>
          <h2 class="fs-title">What's Your Last Name?</h2>

            <%= f.text_field :last_name, value: "" %>

            <br>
            
            <input type="button" name="previous" class="previous action-button btn btn-default" value="Previous" />
            <input type="button" name="next" class="next action-button btn btn-default" value="Next" />

        </fieldset>

        <fieldset id='fs-age'>
          <h2 class="fs-title">How old are you?</h2>

            <%= f.number_field :age, min: 5, max: 99 %>

            <br>

            <input type="button" name="previous" class="previous action-button btn btn-default" value="Previous" />
            <input type="button" name="next" class="next action-button btn btn-default" value="Next" />

        </fieldset>

        <fieldset id='fs-email'>
          <h2 class="fs-title">What's Your Email?</h2>
            <h3 class='fs-subtitle'>(or your parent's if you're under 13)</h3>

            <%= f.text_field :email, value: "" %>

            <br>

            <input type="button" name="previous" class="previous action-button btn btn-default" value="Previous" />
            <input type="button" name="next" class="next action-button btn btn-default" value="Next" />


        </fieldset>

        <fieldset id='fs-password'>
          <h2 class="fs-title">Pick a password!</h2>

            <%= f.password_field :password %>
              
            <h3 class='fs-subtitle'>(and once more just to be sure!)</h3>

            <%= f.password_field :password_confirmation %>

            <br>

          <input type="button" name="previous" class="previous action-button btn btn-default" value="Previous" />
          <input type="button" name="next" class="next action-button btn btn-default" value="Next" />

        </fieldset>

        <fieldset id='fs-submit'>
          <h2 class="fs-title">Good to go?</h2>
          
          <input type="button" name="previous" class="previous action-button btn btn-default" value="Previous" />

          <%= f.submit "Yep!", class: 'btn btn-default' %>

        </fieldset>

      <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/welcome.html.erb
  <!-- Background image -->
<div class="museum-image">
  <%= image_tag "new-background1.jpg" %>
</div>

<div class="museum-image-1">
  <%= image_tag "new-background.jpg" %>
</div>

<div class="mission-slide">
  <%= image_tag "mission.png" %>
  <div class="background-mission-slide"></div>
</div>

<!-- Supergeek challenge logo -->
<div class="challenge-logo">
  <%= image_tag "tsngChallenge.png" %>
</div>


<!-- Large button group -->

<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#modal-fullscreen">
  Sign Up
</button>

<button type="button" class="btn btn-primary btn-lg" onclick="location.href='tasks#index'">
  Quick Start!
</button>

<div class="modal modal-fullscreen fade" id="modal-fullscreen" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
      </div>
      <div class="modal-body">

      <%= form_for current_user do |f| %>

        <fieldset id='fs-username'>
          <h2 class="fs-title">Your Profile</h2>
            <h3 class="fs-subtitle" id='icon-select'>What do you want to call yourself for this mission? You don't have to use your real name.</h3>

              <%= f.text_field :username, value: "" %>

              <input type="button" name="next" class="next action-button btn btn-default" value="Next" />

        </fieldset>

        <fieldset id='fs-icon'>
          <h2 class="fs-title">Choose your avatar</h2>
            <div class='container'>
              <%= f.label :icon_boy, 'boy' do %>
                <%= image_tag "icon_boy.png", id:'icon' %>
              <%end%>
              <%= f.label :icon_girl, 'girl' do %>
                <%= image_tag "icon_girl.png", id: 'icon' %>
              <%end%>

              <br>
  
              <%= f.radio_button :icon, 'boy'  %>
              <%= f.radio_button :icon, 'girl', value: 'girl' %>

            </div>
            
            <input type="button" name="previous" class="previous action-button btn btn-default" id='icon-action' value="Previous" />
            <input type="button" name="next" class="next action-button btn btn-default" id='icon-action' value="Next" />

        </fieldset>

        <fieldset id='fs-submit'>
          <h2 class="fs-title">Ready?</h2>

          <input type="button" name="previous" class="previous action-button btn btn-default" id='icon-submit' value="Previous" />
          <%= f.submit "Let's Go!", class: 'btn btn-default', id: 'icon-submit' %>

        </fieldset>

      <% end %>
      

       <button type="button" class="btn btn-default" onclick="location.href='tasks#index'">Skip</button>

      </div>
    </div>
  </div>
</div>